### ISSUE TITLE
404 Error on Google+ Link

### ISSUE THREAD

**Issue by mrseidel** [pbeens/challenges#1]
The goo.gl link found on Line 1 [here](https://github.com/pbeens/challenges/blob/1fc4ea953c7b2abd3d1507495ff69f2aae4a97e8/GooglePlus_CodingPuzzles_WordSearch/readme.txt#L1) seems to take you to a 404 Error page.

**Comment by pbeens** [comment]
Thanks. I've updated the [readme](https://github.com/pbeens/challenges/blob/master/GooglePlus%20CodingPuzzles%20WordSearch/readme.txt) to reflect that that Google+ community no longer exists. Good catch.
